"""add input_context to job_steps

Revision ID: 8c117703e686
Revises: ba9e42ab3499
Create Date: 2026-09-18 22:51:17.990255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c117703e686'
down_revision: Union[str, Sequence[str], None] = 'ba9e42ab3499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_context', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_steps', schema=None) as batch_op:
        batch_op.drop_column('input_context')

    # ### end Alembic commands ###
