"""add creative_roles, role_executions, messages tables

Revision ID: ba9e42ab3499
Revises: d4cbfb17ec67
Create Date: 2026-09-18 22:31:57.334676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9e42ab3499'
down_revision: Union[str, Sequence[str], None] = 'd4cbfb17ec67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creative_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('output_format', sa.String(length=50), nullable=False),
    sa.Column('suggested_next_role', sa.String(length=255), nullable=True),
    sa.Column('model_override', sa.String(length=255), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creative_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_roles_name'), ['name'], unique=True)

    op.create_table('role_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_step_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('input_brief', sa.Text(), nullable=False),
    sa.Column('output_deliverable', sa.Text(), nullable=True),
    sa.Column('suggested_next_role', sa.String(length=255), nullable=True),
    sa.Column('model_used', sa.String(length=255), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_step_id'], ['job_steps.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['creative_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_executions_job_step_id'), ['job_step_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_executions_role_id'), ['role_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM', 'USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['role_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_execution_id'), ['execution_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_execution_id'))

    op.drop_table('messages')
    with op.batch_alter_table('role_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_executions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_executions_job_step_id'))

    op.drop_table('role_executions')
    with op.batch_alter_table('creative_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_roles_name'))

    op.drop_table('creative_roles')
    # ### end Alembic commands ###
