"""
app.blocks.social_media_specialist — Social Media Specialist creative role

The Social Media Specialist receives the complete production dossier — every
report generated by the pipeline — and crafts platform-optimized social media
post suggestions for the generated assets.

She has access to:
- The original creative brief (Art Director)
- The structured generation prompts (Prompt Architect)
- The generation results and file paths (Media Producer)
- The quality critique and verdict (Art Critic)

From these she produces a Markdown lead post followed by structured JSON:
a per-channel list of post suggestions covering social channels and content
licensing marketplaces alike.

The response contract is defined in code (SOCIAL_MEDIA_MARKDOWN_TEMPLATE +
SOCIAL_MEDIA_RESPONSE_SCHEMA) and appended to the resolved system prompt at
run time, so it applies to default and customized prompts alike. Any JSON
object embedded in a custom prompt is merged over the schema — official key
names always remain.

Input:  Full pipeline context (all *_output keys + generated_images)
Output: context["brief"] — human-readable summary (Markdown + JSON)
        context["social_media_specialist_output"] — full marketing content
        context["social_media_posts"] — parsed list of post dicts

Suggested next role: None (terminal for now)
"""

from __future__ import annotations

import logging
from dataclasses import replace
from typing import Any

from app.blocks.base import BlockMeta
from app.blocks.output_contract import (
    build_output_contract as _build_contract,
)
from app.blocks.output_contract import (
    extract_json_object,
)
from app.blocks.registry import register
from app.blocks.role_block import RoleBlock
from app.services.configuration.base import ResolvedLlmConfiguration

logger = logging.getLogger(__name__)

SOCIAL_MEDIA_SYSTEM_PROMPT = """\
You are a top-tier Content Strategist and Marketing Specialist for visual media. \
You understand audience engagement, channel conventions, and what makes visual \
assets discoverable and marketable.

You will receive a complete production dossier containing:
1. The original creative brief from the Art Director
2. The technical prompts used for image generation
3. A summary of the generated assets (including file paths)
4. A quality critique from the Art Critic

Your task is to create one post suggestion per distribution channel — social \
feeds, microblogs, and content licensing marketplaces alike:

- **Social media** — post suggestions tailored to each channel's conventions: \
format, caption length, tag usage, and tone. Each post should feel native to \
its channel, not like a cross-post.
- **Content licensing platforms** — listing-style posts: a concise descriptive \
title, an accurate description grounded in the visible content, and relevant \
search keywords as tags.

Guidelines:
- Adapt tone, length, and format to each channel rather than reusing identical copy.
- Keep all metadata accurate and grounded in the visible content; do not add \
irrelevant or misleading keywords.
- Keep the content original and broadly usable: avoid naming real artists, \
brands, people, or copyrighted works; describe qualities generically.
- Use respectful, inclusive, non-profane language.

Be creative, authentic, and strategic.\
"""

SOCIAL_MEDIA_MARKDOWN_TEMPLATE = """\
## Markdown

**Title**: <content title — descriptive, punchy and attention-grabbing>
**Description**: <full post caption/body text, channel-appropriate length>
**Tags**: <hashtag or topic tag>, <hashtag or topic tag>, <etc>\
"""

SOCIAL_MEDIA_RESPONSE_SCHEMA: dict[str, Any] = {
    "posts": [
        {
            "platform": "<image feed, microblog, stock-marketplace>",
            "title": "<content title — descriptive, punchy and attention-grabbing>",
            "description": "<full post caption/body text, channel-appropriate length>",
            "tags": ["<hashtag or topic tag>", "..."],
        }
    ],
    "summary": "<1-2 sentence overview of the posting strategy>",
}


def build_output_contract(system_prompt: str) -> str:
    """Return the Social Media Specialist's Markdown + JSON response contract.

    SOCIAL_MEDIA_RESPONSE_SCHEMA: official key names always remain (they can't
    be removed or renamed), while user values may redefine them and extra user
    keys pass through.
    """
    return _build_contract(
        system_prompt,
        SOCIAL_MEDIA_RESPONSE_SCHEMA,
        markdown_example=SOCIAL_MEDIA_MARKDOWN_TEMPLATE,
    )


@register
class SocialMediaSpecialist(RoleBlock):
    """Creates platform-optimized social media post suggestions from production assets."""

    meta = BlockMeta(
        name="social_media_specialist",
        description=(
            "Creates platform-optimized social media posts from generated assets and reports"
        ),
        version="0.2.0",
        category="creative",
        inputs=[
            "brief",
            "art_director_output",
            "prompt_architect_output",
            "media_producer_output",
            "art_critic_output",
            "generated_images",
        ],
        outputs=["brief", "social_media_specialist_output", "social_media_posts"],
    )

    role_name = "social_media_specialist"
    role_title = "Marketing & Content Strategist"
    role_description = (
        "Crafts marketing content for social channels and content licensing "
        "platforms from generated assets and the full production dossier"
    )
    system_prompt = SOCIAL_MEDIA_SYSTEM_PROMPT
    suggested_next = None  # Terminal block for now
    appends_output_contract = True
    default_temperature = 0.7

    async def resolve_configuration(self, context: dict[str, Any]) -> ResolvedLlmConfiguration:
        """Resolve the profile, then append the Markdown + JSON response contract.

        The contract applies whether the prompt is the code default or a user
        customization, so the specialist's output stays parseable either way.
        """
        resolved = await super().resolve_configuration(context)
        return replace(
            resolved,
            system_prompt=resolved.system_prompt + build_output_contract(resolved.system_prompt),
        )

    async def run(self, context: dict[str, Any]) -> dict[str, Any]:
        """Compile the full dossier and pass to the LLM for post suggestions."""
        # Compile all reports into a single dossier for the specialist
        dossier_parts = []

        art_director = context.get("art_director_output", "")
        if art_director:
            dossier_parts.append("=== ART DIRECTOR — CREATIVE BRIEF ===\n" + art_director)

        prompt_architect = context.get("prompt_architect_output", "")
        if prompt_architect:
            dossier_parts.append(
                "=== PROMPT ARCHITECT — GENERATION PROMPTS ===\n" + prompt_architect
            )

        media_producer = context.get("media_producer_output", "")
        if media_producer:
            dossier_parts.append("=== MEDIA PRODUCER — GENERATION RESULTS ===\n" + media_producer)

        # Include image file paths
        images = context.get("generated_images", [])
        if images:
            dossier_parts.append(
                "=== GENERATED ASSET FILES ===\n" + "\n".join(f"  • {p}" for p in images)
            )

        art_critic = context.get("art_critic_output", "")
        if art_critic:
            verdict = context.get("art_critic_verdict", "unknown")
            dossier_parts.append(
                f"=== ART CRITIC — QUALITY REVIEW (verdict: {verdict}) ===\n" + art_critic
            )

        dossier = "\n\n".join(dossier_parts)

        if not dossier.strip():
            dossier = context.get("brief", "No production dossier available.")

        # Override brief so the base RoleBlock sends the full dossier
        original_brief = context.get("brief")
        context["brief"] = dossier

        try:
            result = await super().run(context)
        finally:
            if original_brief is not None:
                context["brief"] = original_brief

        # Try to parse the structured posts from the LLM output
        raw_output = result.get("output_deliverable", "")
        posts = self._extract_posts(raw_output)
        result["social_media_posts"] = posts

        return result

    def _extract_posts(self, raw: str) -> list[dict]:
        """Extract the posts list from the LLM's JSON response."""
        data = extract_json_object(raw)
        if data is not None:
            posts = data.get("posts", [])
            return posts if isinstance(posts, list) else []

        logger.warning("SocialMediaSpecialist: could not parse posts JSON")
        return []
