"""
app.blocks.social_media_specialist — Social Media Specialist creative role

The Social Media Specialist receives the complete production dossier — every
report generated by the pipeline — and crafts platform-optimized social media
post suggestions for the generated assets.

She has access to:
- The original creative brief (Art Director)
- The structured generation prompts (Prompt Architect)
- The generation results and file paths (Media Producer)
- The quality critique and verdict (Art Critic)

From these she produces structured JSON with per-platform post suggestions
including titles, descriptions, tags, and platform-specific metadata.

Input:  Full pipeline context (all *_output keys + generated_images)
Output: context["brief"] — human-readable summary
        context["social_media_specialist_output"] — full JSON post suggestions
        context["social_media_posts"] — parsed list of post dicts

Suggested next role: None (terminal for now)
"""

from __future__ import annotations

import json
import logging
from typing import Any

from app.blocks.base import BlockMeta
from app.blocks.registry import register
from app.blocks.role_block import RoleBlock

logger = logging.getLogger(__name__)

SOCIAL_MEDIA_SYSTEM_PROMPT = """\
You are a top-tier Social Media Strategist and Content Creator with expertise \
across all major platforms. You understand algorithmic reach, engagement \
psychology, and platform-specific best practices.

You will receive a complete production dossier containing:
1. The original creative brief from the Art Director
2. The technical prompts used for image generation
3. A summary of the generated assets (including file paths)
4. A quality critique from the Art Critic

Your task is to create platform-optimized social media post suggestions for \
the generated visual content. Produce a JSON response with this exact structure \
(no markdown fences, no preamble):

{
  "posts": [
    {
      "platform": "<instagram|twitter|linkedin|facebook|pinterest|tiktok|threads>",
      "title": "<post title or headline — keep punchy and attention-grabbing>",
      "description": "<the full post caption/body text, platform-appropriate length>",
      "tags": ["<hashtag1>", "<hashtag2>", "...up to 30 for IG, 5 for Twitter, etc."],
      "alt_text": "<accessibility alt-text describing the image for screen readers>",
      "suggested_time": "<best posting time, e.g. 'Tuesday 10am EST'>",
      "content_type": "<image|carousel|reel|story>",
      "call_to_action": "<suggested CTA, e.g. 'Link in bio', 'Save for later'>",
      "notes": "<any platform-specific tips or considerations>"
    }
  ],

  "brand_voice": "<1-2 sentence summary of the tone/voice used across posts>",

  "campaign_tags": ["<3-5 overarching campaign hashtags>"],

  "seo_keywords": ["<5-10 SEO keywords for discoverability>"],

  "summary": "<brief executive summary of the social media strategy>"
}

Platform guidelines:
- **Instagram**: Up to 2,200 chars caption, 30 hashtags max, visual-first, use line breaks
- **Twitter/X**: 280 chars max, 2-5 hashtags, punchy and conversational
- **LinkedIn**: Professional tone, 1,300 chars ideal, 3-5 hashtags, thought leadership angle
- **Facebook**: 1-2 paragraphs, conversational, encourage shares and comments
- **Pinterest**: SEO-rich description, 500 chars, keyword-heavy tags
- **TikTok**: Casual, trend-aware, 150 chars ideal, trending hashtags
- **Threads**: Conversational, 500 chars, minimal hashtags

Metadata and compliance rules:
- Never put artist or photographer names, real or notable people, fictional \
characters, copyrighted works, brands, company names, government-agency names, \
logos, trademarks, protected property, or other contributors in titles, captions, \
tags, alt text, campaign tags, or SEO keywords.
- Never use "in the style of," "inspired by," "influenced by," "in the tradition \
of," or "drawing on" a creator or creative work.
- Do not state or imply that fictional content depicts an actual newsworthy event.
- Use only accurate, relevant metadata grounded in visible content; do not add \
irrelevant or misleading keywords.
- Use respectful, inclusive, non-profane language. Do not publish copy that promotes \
hateful or discriminatory content, nudity, sexual content, exploitation of minors, \
self-harm, violence, gore, illegal themes, or obscene gestures.
- If the dossier contains a restricted term, omit it and describe only generic, \
non-infringing visual qualities. Never repeat restricted wording in any output field.

Produce posts for at least Instagram, Twitter/X, and LinkedIn. Add others \
if the content is a good fit.

Be creative, authentic, and strategic. Each post should feel native to its \
platform, not like a cross-post. Respond with ONLY the JSON object.\
"""


@register
class SocialMediaSpecialist(RoleBlock):
    """Creates platform-optimized social media post suggestions from production assets."""

    meta = BlockMeta(
        name="social_media_specialist",
        description=(
            "Creates platform-optimized social media posts from generated assets and reports"
        ),
        version="0.1.0",
        category="creative",
        inputs=[
            "brief",
            "art_director_output",
            "prompt_architect_output",
            "media_producer_output",
            "art_critic_output",
            "generated_images",
        ],
        outputs=["brief", "social_media_specialist_output", "social_media_posts"],
    )

    role_name = "social_media_specialist"
    role_title = "Social Media Strategist & Content Creator"
    role_description = (
        "Crafts platform-optimized social media post suggestions "
        "from generated assets and the full production dossier"
    )
    system_prompt = SOCIAL_MEDIA_SYSTEM_PROMPT
    suggested_next = None  # Terminal block for now
    default_temperature = 0.7

    async def run(self, context: dict[str, Any]) -> dict[str, Any]:
        """Compile the full dossier and pass to the LLM for post suggestions."""
        # Compile all reports into a single dossier for the specialist
        dossier_parts = []

        art_director = context.get("art_director_output", "")
        if art_director:
            dossier_parts.append("=== ART DIRECTOR — CREATIVE BRIEF ===\n" + art_director)

        prompt_architect = context.get("prompt_architect_output", "")
        if prompt_architect:
            dossier_parts.append(
                "=== PROMPT ARCHITECT — GENERATION PROMPTS ===\n" + prompt_architect
            )

        media_producer = context.get("media_producer_output", "")
        if media_producer:
            dossier_parts.append("=== MEDIA PRODUCER — GENERATION RESULTS ===\n" + media_producer)

        # Include image file paths
        images = context.get("generated_images", [])
        if images:
            dossier_parts.append(
                "=== GENERATED ASSET FILES ===\n" + "\n".join(f"  • {p}" for p in images)
            )

        art_critic = context.get("art_critic_output", "")
        if art_critic:
            verdict = context.get("art_critic_verdict", "unknown")
            dossier_parts.append(
                f"=== ART CRITIC — QUALITY REVIEW (verdict: {verdict}) ===\n" + art_critic
            )

        dossier = "\n\n".join(dossier_parts)

        if not dossier.strip():
            dossier = context.get("brief", "No production dossier available.")

        # Override brief so the base RoleBlock sends the full dossier
        original_brief = context.get("brief")
        context["brief"] = dossier

        try:
            result = await super().run(context)
        finally:
            if original_brief is not None:
                context["brief"] = original_brief

        # Try to parse the structured posts from the LLM output
        raw_output = result.get("output_deliverable", "")
        posts = self._extract_posts(raw_output)
        result["social_media_posts"] = posts

        return result

    def _extract_posts(self, raw: str) -> list[dict]:
        """Extract the posts list from the LLM's JSON response."""
        text = raw.strip()

        # Strip markdown fences
        if text.startswith("```"):
            first_nl = text.index("\n")
            text = text[first_nl + 1 :]
            if text.endswith("```"):
                text = text[:-3]
            text = text.strip()

        # Try direct parse
        try:
            data = json.loads(text)
            return data.get("posts", [])
        except json.JSONDecodeError:
            pass

        # Try finding JSON in text
        start = text.find("{")
        end = text.rfind("}")
        if start != -1 and end > start:
            try:
                data = json.loads(text[start : end + 1])
                return data.get("posts", [])
            except json.JSONDecodeError:
                pass

        logger.warning("SocialMediaSpecialist: could not parse posts JSON")
        return []
