"""
app.blocks.social_media_specialist — Social Media Specialist creative role

The Social Media Specialist receives the complete production dossier — every
report generated by the pipeline — and crafts platform-optimized social media
post suggestions for the generated assets.

She has access to:
- The original creative brief (Art Director)
- The structured generation prompts (Prompt Architect)
- The generation results and file paths (Media Producer)
- The quality critique and verdict (Art Critic)

From these she produces structured JSON with marketing content for two
channel categories: per-channel social media post suggestions and listing
metadata for content licensing platforms.

The JSON response contract is defined in code (SOCIAL_MEDIA_RESPONSE_SCHEMA)
and appended to the resolved system prompt at run time, so it applies to
default and customized prompts alike. Any JSON object embedded in a custom
prompt is merged over the schema — official key names always remain.

Input:  Full pipeline context (all *_output keys + generated_images)
Output: context["brief"] — human-readable summary
        context["social_media_specialist_output"] — full JSON marketing content
        context["social_media_posts"] — parsed list of post dicts

Suggested next role: None (terminal for now)
"""

from __future__ import annotations

import json
import logging
from dataclasses import replace
from typing import Any

from app.blocks.base import BlockMeta
from app.blocks.prompt_architect import build_output_contract
from app.blocks.registry import register
from app.blocks.role_block import RoleBlock
from app.services.configuration.base import ResolvedLlmConfiguration

logger = logging.getLogger(__name__)

SOCIAL_MEDIA_SYSTEM_PROMPT = """\
You are a top-tier Content Strategist and Marketing Specialist for visual media. \
You understand audience engagement, channel conventions, and what makes visual \
assets discoverable and marketable.

You will receive a complete production dossier containing:
1. The original creative brief from the Art Director
2. The technical prompts used for image generation
3. A summary of the generated assets (including file paths)
4. A quality critique from the Art Critic

Your task is to create marketing content for the generated assets across two \
categories of distribution channels:

- **Social media** — post suggestions tailored to each channel's conventions: \
format, caption length, tag usage, and tone. Each post should feel native to \
its channel, not like a cross-post.
- **Content licensing platforms** — listing metadata for each asset: a concise \
descriptive title, an accurate description grounded in the visible content, \
relevant search keywords, and a suggested category.

Guidelines:
- Adapt tone, length, and format to each channel rather than reusing identical copy.
- Keep all metadata accurate and grounded in the visible content; do not add \
irrelevant or misleading keywords.
- Keep the content original and broadly usable: avoid naming real artists, \
brands, people, or copyrighted works; describe qualities generically.
- Use respectful, inclusive, non-profane language.

Be creative, authentic, and strategic.\
"""

SOCIAL_MEDIA_RESPONSE_SCHEMA: dict[str, Any] = {
    "posts": [
        {
            "platform": "<social channel name or type, e.g. image feed, microblog, "
            "professional network, short-video app>",
            "title": "<post title or headline — punchy and attention-grabbing>",
            "description": "<full post caption/body text, channel-appropriate length>",
            "tags": ["<hashtag or topic tag>", "..."],
            "alt_text": "<accessibility alt-text describing the image>",
            "suggested_time": "<best posting time, e.g. 'Tuesday 10am'>",
            "content_type": "<format suited to the channel: single image, carousel, "
            "short video, story>",
            "call_to_action": "<suggested CTA, e.g. 'Link in bio', 'Save for later'>",
            "notes": "<channel-specific tips or considerations>",
        }
    ],
    "licensing": [
        {
            "platform": "<content licensing platform or marketplace>",
            "title": "<concise, descriptive asset title>",
            "description": "<accurate listing description grounded in the visible content>",
            "keywords": ["<relevant search keyword>", "..."],
            "category": "<suggested asset category>",
            "notes": "<platform-specific considerations>",
        }
    ],
    "brand_voice": "<1-2 sentence summary of the tone/voice used>",
    "campaign_tags": ["<3-5 overarching campaign tags>"],
    "seo_keywords": ["<5-10 search keywords for discoverability>"],
    "summary": "<brief executive summary of the marketing strategy>",
}


@register
class SocialMediaSpecialist(RoleBlock):
    """Creates platform-optimized social media post suggestions from production assets."""

    meta = BlockMeta(
        name="social_media_specialist",
        description=(
            "Creates platform-optimized social media posts from generated assets and reports"
        ),
        version="0.2.0",
        category="creative",
        inputs=[
            "brief",
            "art_director_output",
            "prompt_architect_output",
            "media_producer_output",
            "art_critic_output",
            "generated_images",
        ],
        outputs=["brief", "social_media_specialist_output", "social_media_posts"],
    )

    role_name = "social_media_specialist"
    role_title = "Marketing & Content Strategist"
    role_description = (
        "Crafts marketing content for social channels and content licensing "
        "platforms from generated assets and the full production dossier"
    )
    system_prompt = SOCIAL_MEDIA_SYSTEM_PROMPT
    suggested_next = None  # Terminal block for now
    default_temperature = 0.7

    async def resolve_configuration(self, context: dict[str, Any]) -> ResolvedLlmConfiguration:
        """Resolve the profile, then append the canonical JSON response contract.

        The contract applies whether the prompt is the code default or a user
        customization, so the specialist's output stays parseable either way.
        """
        resolved = await super().resolve_configuration(context)
        return replace(
            resolved,
            system_prompt=resolved.system_prompt
            + build_output_contract(resolved.system_prompt, SOCIAL_MEDIA_RESPONSE_SCHEMA),
        )

    async def run(self, context: dict[str, Any]) -> dict[str, Any]:
        """Compile the full dossier and pass to the LLM for post suggestions."""
        # Compile all reports into a single dossier for the specialist
        dossier_parts = []

        art_director = context.get("art_director_output", "")
        if art_director:
            dossier_parts.append("=== ART DIRECTOR — CREATIVE BRIEF ===\n" + art_director)

        prompt_architect = context.get("prompt_architect_output", "")
        if prompt_architect:
            dossier_parts.append(
                "=== PROMPT ARCHITECT — GENERATION PROMPTS ===\n" + prompt_architect
            )

        media_producer = context.get("media_producer_output", "")
        if media_producer:
            dossier_parts.append("=== MEDIA PRODUCER — GENERATION RESULTS ===\n" + media_producer)

        # Include image file paths
        images = context.get("generated_images", [])
        if images:
            dossier_parts.append(
                "=== GENERATED ASSET FILES ===\n" + "\n".join(f"  • {p}" for p in images)
            )

        art_critic = context.get("art_critic_output", "")
        if art_critic:
            verdict = context.get("art_critic_verdict", "unknown")
            dossier_parts.append(
                f"=== ART CRITIC — QUALITY REVIEW (verdict: {verdict}) ===\n" + art_critic
            )

        dossier = "\n\n".join(dossier_parts)

        if not dossier.strip():
            dossier = context.get("brief", "No production dossier available.")

        # Override brief so the base RoleBlock sends the full dossier
        original_brief = context.get("brief")
        context["brief"] = dossier

        try:
            result = await super().run(context)
        finally:
            if original_brief is not None:
                context["brief"] = original_brief

        # Try to parse the structured posts from the LLM output
        raw_output = result.get("output_deliverable", "")
        posts = self._extract_posts(raw_output)
        result["social_media_posts"] = posts

        return result

    def _extract_posts(self, raw: str) -> list[dict]:
        """Extract the posts list from the LLM's JSON response."""
        text = raw.strip()

        # Strip markdown fences
        if text.startswith("```"):
            first_nl = text.index("\n")
            text = text[first_nl + 1 :]
            if text.endswith("```"):
                text = text[:-3]
            text = text.strip()

        # Try direct parse
        try:
            data = json.loads(text)
            return data.get("posts", [])
        except json.JSONDecodeError:
            pass

        # Try finding JSON in text
        start = text.find("{")
        end = text.rfind("}")
        if start != -1 and end > start:
            try:
                data = json.loads(text[start : end + 1])
                return data.get("posts", [])
            except json.JSONDecodeError:
                pass

        logger.warning("SocialMediaSpecialist: could not parse posts JSON")
        return []
